apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook
  namespace: kargo-helm-ff
spec:
  shard: kargo-agent
  subscriptions:
  - image:
      repoURL: ghcr.io/va7ish/guestbook
      imageSelectionStrategy: SemVer

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: features
  namespace: kargo-helm-ff
spec:
  shard: kargo-agent
  subscriptions:
  - git:
      branch: main
      commitSelectionStrategy: NewestFromBranch
      discoveryLimit: 20
      repoURL: https://github.com/va7ish/kargo-helm-ff.git
      includePaths:
      - base/feature-flags.yaml
