apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-helm-ff-gb
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/va7ish/kargo-helm-ff.git
      revision: HEAD
      directories:
      - path: env/*
  template:
    metadata:
      name: kargo-helm-ff-{{path.basename}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-helm-ff:{{path.basename}}
    spec:
      destination:
        namespace: kargo-helm-ff-{{path.basename}}
        name: mac2
      project: kargo-helm-ff
      source:
        path: charts/guestbook
        repoURL: https://github.com/va7ish/kargo-helm-ff.git
        helm:
          valueFiles:
          - "/env/{{path.basename}}/values.yaml"
          - "/env/{{path.basename}}/feature-flags.yaml"
