apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-helm-ff
spec:
  project: kargo-helm-ff
  source:
    repoURL: https://github.com/dhpup/kargo-helm-ff.git
    path: kargo
  destination:
    server: https://b5bxdj947v9xturb-cplane.kargosvcs.akuity.cloud
  syncPolicy:
    syncOptions:
    - CreateNamespace=true